=== proton88/kursPVT/Less14/src/xmlxsd/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/library"
	xmlns:tns="http://www.example.org/library">
	
	<element name="listBook">
		<complexType>
			<sequence>
				<element name="Book" type="tns:Book" minOccurs="1" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	
	<complexType name="Book">
		<all>
			<element name="author" type="tns:AuthorType"/>
			<element name="title" type="string"/>
			<element name="genre" type="tns:Genre"/>
 			<element name="price" type="integer"/>
		</all>
		<attribute name="id" type="int" use="required"/>
	</complexType>	
	<simpleType name="AuthorType">
		<restriction base="string">
			<pattern value="[A-Z]([a-z]*)"/>
		</restriction>
	</simpleType>
	<simpleType name="Genre">
		<restriction base="string">
			<enumeration value="fantastic"/>
			<enumeration value="science"/>
			<enumeration value="detective"/>
			<enumeration value="biography"/>
			<enumeration value="history"/>
			<enumeration value="humor"/>
		</restriction>
	</simpleType>
</schema>

=== proton88/kursPVT/Less14/src/xmlxsd/library.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><tc:listBook xmlns:tc="http://www.example.org/library" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/library library.xsd">

    <Book id="1">
        <author>Ozhegov</author>
        <title>vocabulary</title>
        <price>20</price>
        <genre>science</genre>
    </Book>

    <Book id="2">
        <author>God</author>
        <title>bible</title>
        <price>25</price>
        <genre>science</genre>
    </Book>

<Book id="3"><author>Tolkien</author><title>Lord of the rings</title><price>30</price><genre>fantastic</genre></Book>
</tc:listBook>
